export enum CurrencyCode {
  GBP = 'GBP', // UK Pound
  CZK = 'CZK', // Czech Koruna
  LVL = 'LVL', // Latvian Lat
  CHF = 'CHF', // Swiss Franc
  HRK = 'HRK', // Croatian Kuna
  DKK = 'DKK', // Danish Krone
  KRW = 'KRW', // Korean Won
  SEK = 'SEK', // Swedish Krona
  TRY = 'TRY', // Turkish Lira
  HUF = 'HUF', // Hungarian Forint
  BRL = 'BRL', // Brazilian Real
  LTL = 'LTL', // Lithuanian Litas
  BGN = 'BGN', // Bulgarian Lev
  PLN = 'PLN', // Polish Zloty
  USD = 'USD', // US Dollar
  RUB = 'RUB', // Russian Ruble
  JPY = 'JPY', // Japanese Yen
  RON = 'RON', // Romanian Leu
  NOK = 'NOK', // Norwegian Krone
  AUD = 'AUD', // Australian Dollar
  ILS = 'ILS', // Israeli Shekel
  NZD = 'NZD', // New Zealand Dollar
  IDR = 'IDR', // Indonesian Rupiah
  PHP = 'PHP', // Philippine Peso
  EUR = 'EUR', // Euro
  CAD = 'CAD', // Canadian Dollar
  CNY = 'CNY', // Chinese Yuan
  HKD = 'HKD', // Hong Kong Dollar
  INR = 'INR', // Indian Rupee
  MXN = 'MXN', // Mexican Peso
  MYR = 'MYR', // Malaysian Ringgit
  ZAR = 'ZAR', // South African Rand
  THB = 'THB', // Thai Baht
  SGD = 'SGD', // Singapore Dollar
}

export enum CurrencyName {
  GBP = 'UK Pound',
  CZK = 'Czech Koruna',
  LVL = 'Latvian Lat',
  CHF = 'Swiss Franc',
  HRK = 'Croatian Kuna',
  DKK = 'Danish Krone',
  KRW = 'Korean Won',
  SEK = 'Swedish Krona',
  TRY = 'Turkish Lira',
  HUF = 'Hungarian Forint',
  BRL = 'Brazilian Real',
  LTL = 'Lithuanian Litas',
  BGN = 'Bulgarian Lev',
  PLN = 'Polish Zloty',
  USD = 'US Dollar',
  RUB = 'Russian Ruble',
  JPY = 'Japanese Yen',
  RON = 'Romanian Leu',
  NOK = 'Norwegian Krone',
  AUD = 'Australian Dollar',
  ILS = 'Israeli Shekel',
  NZD = 'New Zealand Dollar',
  IDR = 'Indonesian Rupiah',
  PHP = 'Philippine Peso',
  EUR = 'Euro',
  CAD = 'Canadian Dollar',
  CNY = 'Chinese Yuan',
  HKD = 'Hong Kong Dollar',
  INR = 'Indian Rupee',
  MXN = 'Mexican Peso',
  MYR = 'Malaysian Ringgit',
  ZAR = 'South African Rand',
  THB = 'Thai Baht',
  SGD = 'Singapore Dollar',
}
