services:
  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: production
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: 760381
      TYPEORM_DATABASE: postgres
      TYPEORM_ENTITIES: src/entity/**/*.ts
      TYPEORM_LOGGING: false
    volumes:
      - ../../src:/app/src
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 760381
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
